### ISSUE TITLE
Dependencies seems too restrictive

### ISSUE THREAD

**Issue by bewantbe** [visor-tech/visor-py#3]
The package dependencies:

https://github.com/visor-tech/visor-py/blob/5488ecc2c93bd3c664dbd24d0d7323ada4f0a15b/pyproject.toml#L19-L24

Is currently too restrictive so that might easily conflict with other packages in the environments or forced changing of environment unintentionally.
Probably consider relax it to '>='?

**Comment by i-z-j** [comment]
addressed in release [v2024.12.3](https://github.com/visor-tech/visor-py/releases/tag/v2024.12.3)
